# Generated by Django 2.1.5 on 2019-01-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marbar',
            old_name='user',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='marbar',
            name='title',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
