# Generated by Django 2.1.5 on 2019-02-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190131_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='marbar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.MarBar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
